# Generated by Django 5.1.4 on 2024-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='status',
            field=models.CharField(blank=True, choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=10),
        ),
    ]
